export const dataProjects = [
  {
    id: '1',
    title: "Master Question",
    description: "lorem ipsum nfgdfg ethewtru wegasgesh st eth  eth ",
    link: "https://google.com",
    github: "https://github.com",
    image: "/projects_images/master_question.png",
    tags: ["React", "Javascript", "CSS"],
    youtube: "https://www.youtube.com",
  },
  {
    id: '2',
    title: "Project 1",
    description: "lorem ipsum nfgdfg ethewtru wegasgesh st eth  eth ",
    link: "https://google.com",
    github: "https://github.com",
    image: "https://picsum.photos/200/301",
    tags: ["react", "javascript", "css"],
    youtube: "https://www.youtube.com",
  },
  {
    id: '3',
    title: "Project 1",
    description: "lorem ipsum nfgdfg ethewtru wegasgesh st eth  eth ",
    link: "https://google.com",
    github: "https://github.com",
    image: "https://picsum.photos/202/300",
    tags: ["react", "javascript", "css"],
    youtube: "https://www.youtube.com",
  },
  {
    id: '4',
    title: "Project 1",
    description: "lorem ipsum nfgdfg ethewtru wegasgesh st eth  eth ",
    link: "https://google.com",
    github: "https://github.com",
    image: "https://picsum.photos/205/300",
    tags: ["react", "javascript", "css"],
    youtube: "https://www.youtube.com",
  },
];
